### ISSUE TITLE
UDv2?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-ESL#2]
I'd like to use this corpus for a project. Are there plans to convert it to UDv2? Or is this something I'd have to do myself (e.g. with https://github.com/UniversalDependencies/tools/tree/master/v2-conversion or https://github.com/udapi/udapi-python/tree/master/udapi/block/ud)?

**Comment by berzak** [comment]
Hi Nathan,
we plan to convert to v2, but it may take a while. In the meantime the best option would be to run one of the conversion scripts you linked to.

Best,
Yevgeni

**Comment by nschneid** [comment]
OK, I've run merge.py to download the corpus. The parses all appear to be of the original sentences. Where are the trees for corrected sentences? Am I missing something?

**Comment by berzak** [comment]
I added the files of the corrected sentences to the data folder. If you run merge.py again you should get those as well.

**Comment by nschneid** [comment]
Brilliant. So now I see trees with the corrected sentences.

Looking at the examples in the [paper](http://www.aclweb.org/anthology/P16-1070), I see that "I had to give (to) him water" (`ID=/0100_2000_6/doc1821.xml 21b`) still has *him* as `nmod` in the corrected sentence's tree. Is that an error?

I can't seem to find the sentence "I have to ask you (for) the money of/for the tickets back" in the data.

**Comment by berzak** [comment]
Great!

Yes, that's an annotation error, will fix for the next release.

This sentence is one of ~80 FCE sentences that we used during annotator training, which was also the time when we wrote down most of the annotation guidelines. These sentences didn't make it to the dataset since we didn't annotate the corresponding corrected sentences, and the different annotations for the original sentences were not merged. Hopefully, we will be able to add them in the future (pm me if you are interested to see 6 different annotation versions for these sentences : )).
